application: vkontakte-feed
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: favicon.ico

- url: /images
  static_dir: images

- url: /((?:google|yandex).*\.html)
  static_files: verifications/\1
  upload: verifications

- url: /.*
  script: vkfeed.main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^images.orig(/.*)?
